project_id = "sjjwswpxrjublpmrnoca"

[functions.generate-product-image]
verify_jwt = false

[functions.upload-local-images]
verify_jwt = false

[functions.register-user]
verify_jwt = false

[functions.login-user]
verify_jwt = false

[functions.approve-user]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.complete-order]
verify_jwt = false

[functions.deactivate-user]
verify_jwt = false

[functions.manage-admin]
verify_jwt = false

[functions.manage-site-settings]
verify_jwt = false

[functions.manage-announcements]
verify_jwt = false
